from pathlib import Path
from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings, SettingsConfigDict
from typing import Literal, Optional

BASE_DIR = Path(__file__).resolve().parent.parent

class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    # --- Server ---
    APP_ENV: str = "development"
    APP_PORT: int = 8000

    # --- Gemini ---
    GEMINI_API_KEY: str = ""
    GEMINI_MODEL: str = "gemini-2.0-flash"


    # --- MongoDB ---
    MONGODB_URI: str = "'mongodb+srv://jenabiswajit2005_db_user:T0DEoGQVlt5ViIEC@biswajit1.bihj9fi.mongodb.net/heart_disease_ai'"
    MONGODB_DB_NAME: str = "heart_disease_ai"

    # --- ChromaDB / RAG ---
    CHROMA_PERSIST_DIR: str = str(BASE_DIR / "data" / "knowledge_base" / "chroma_db")
    EMBEDDING_MODEL: str = "all-MiniLM-L6-v2"
    RAG_TOP_K: int = 4

    # --- LLM Provider Settings (gemini or groq) ---
    LLM_PROVIDER: str = "groq"
    GROQ_API_KEY: str = ""
    # Default / fallback model
    GROQ_MODEL: str = "llama-3.1-8b-instant"
    # Agent-specific models
    GROQ_MODEL_RISK: str = "llama-3.3-70b-versatile"       # deep reasoning for risk projection
    GROQ_MODEL_RECOMMENDATION: str = "llama-3.1-8b-instant" # fast structured JSON for recs

    # --- ML model ---
    ML_MODEL_PATH: str = str(BASE_DIR / "ml_models" / "trained" / "heart_disease_model.joblib")
    ML_FEATURE_COLUMNS: list[str] = [
        "Age", "Sex", "Smoking", "Diabetes", "Chest_Pain",\
        "Hypertension", "High_Cholesterol", "Obesity", "Family_History", "Physically_Inactive"
    ]
    ML_TARGET_COLUMN: str = "Heart_Attack_Risk"
    RAW_DATA_PATH: str = str(BASE_DIR / "data" / "raw" / "heart_risk.csv")

settings = Settings()

# --- Pydantic Schemas ---

class PatientInput(BaseModel):
    age: int = Field(..., ge=1, le=120)
    sex: int = Field(..., ge=0, le=1)  # 0 = Female, 1 = Male
    smoking: int = Field(..., ge=0, le=1)
    diabetes: int = Field(..., ge=0, le=1)
    chest_pain: int = Field(..., ge=0, le=1)
    hypertension: int = Field(..., ge=0, le=1)
    high_cholesterol: int = Field(..., ge=0, le=1)
    obesity: int = Field(..., ge=0, le=1)
    family_history: int = Field(..., ge=0, le=1)
    physically_inactive: int = Field(..., ge=0, le=1)

    def to_feature_dict(self) -> dict:
        return {
            "Age": self.age,
            "Sex": self.sex,
            "Smoking": self.smoking,
            "Diabetes": self.diabetes,
            "Chest_Pain": self.chest_pain,
            "Hypertension": self.hypertension,
            "High_Cholesterol": self.high_cholesterol,
            "Obesity": self.obesity,
            "Family_History": self.family_history,
            "Physically_Inactive": self.physically_inactive,
        }

class PredictionResult(BaseModel):
    model_config = {"protected_namespaces": ()}
    risk_label: Literal["Low Risk", "High Risk"]
    risk_probability: float
    risk_score: int
    model_version: str = "v1"

class AgentBreakdown(BaseModel):
    prediction_agent: dict
    risk_analysis_agent: dict
    rag_retrieval_agent: dict
    recommendation_agent: dict
    report_generation_agent: dict

class HealthReport(BaseModel):
    patient_summary: str
    risk_score: int
    risk_level: str
    key_risk_factors: list[str]
    medical_insights: str
    recommendations: list[str]
    preventive_measures: list[str]
    future_outlook: str
    agent_breakdown: AgentBreakdown
    disclaimer: str = (
        "This report is generated by an AI system for informational purposes only, It's only a pre medical measure if you find high risk then immedieately ask about to the doctor "
    )
